name: Test All Streamlit Apps

on:
  push:
    paths:
      - '**.py'
      - '**/requirements.txt'
      - '.test-all-apps.sh'
      - '.github/workflows/test-all-apps.yml'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: List files in workspace
        run: ls -al
      - name: Make test script executable
        run: chmod +x .test-all-apps.sh
      - name: Run all app tests
        run: ././.test-all-apps.sh